version: '3.8'

services:
  app:
    build:
      context: ./agent-api
      dockerfile: Dockerfile
    ports:
      - "5001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./agent-api/vector-store:/app/vector-store
      - ./agent-api/data:/app/data
  agent-ui:
    build:
      context: ./agent-ui
      dockerfile: Dockerfile
    ports:
      - "81:80"
    depends_on:
      - app
